### ISSUE TITLE
Add RAZU CDN token as secret variable

### ISSUE THREAD

**Issue by Simon-Dirks** [Simon-Dirks/view-a-LOD#101]

**Comment by RAZU-WBakker** [comment]
Any iri referring to *.opslag.razu.nl should include a JWT-token. The JWT-token is subdomain-specific, so this implementation should support adding multiple domains with their own secrets. aka:
bunnik.opslag.razu.nl/....  has a different secret than houten.opslag.razu.nl/....

See for the documentation: https://public-assets.scalia.nl/docs/SI-JWTProtection-ScaliaCDN-010323-1338.pdf

**Comment by Simon-Dirks** [comment]
I'm processing link + image URLs through a newly created "CDN service" now. Feel free to edit the function below to handle specific subdomains or more complex regex. Note that since we're not using a back-end, any "secrets" are not secret at all and publicly available in the HTML + js (as well as in this repo). This functionality should allow you, however, to remove the tokens from the URLs in the triple store.

https://github.com/Simon-Dirks/view-a-LOD/blob/3201e19a74d3f3e45f88da6a643fe2e5645bfd9a/src/app/services/cdn.service.ts#L28-L38
